import { ThemeColor } from "../../saigon.types";

export type ListGroupProp = Partial<{
  /**
   * Add .list-group-flush to remove some borders and rounded corners to render list group items edge-to-edge in a parent container (e.g., cards).
   * @default false
   */
  flush: boolean;

  /**
   * Add the .list-group-numbered modifier class (and optionally use an <ol> element) to opt into numbered list group items. Numbers are generated via CSS (as opposed to a <ol>s default browser styling) for better placement inside list group items and to allow for better customization.
   *
   * Numbers are generated by counter-reset on the <ol>, and then styled and placed with a ::before pseudo-element on the <li> with counter-increment and content.
   *
   * @default false
   */
  numbered: boolean;

  /**
   * Add .list-group-horizontal to change the layout of list group items from vertical to horizontal across all breakpoints. Alternatively, choose a responsive variant .list-group-horizontal-{sm|md|lg|xl|xxl} to make a list group horizontal starting at that breakpoint’s min-width.
   *
   * **Currently horizontal list groups cannot be combined with flush list groups**.
   *
   * @default false
   */
  horizontal: boolean;
}>;

export type ListGroupItemProp = Partial<{
  /**
   * @default li
   */
  as: "a" | "li";

  /**
   * Use contextual classes to style list items with a stateful background and color.
   *
   * @default undefined
   */
  variant: ThemeColor;

  /**
   * Add `.active` to a `.list-group-item` to indicate the current active selection.
   *
   * @default false
   */
  active: boolean;

  /**
   * Contextual classes also work with .list-group-item-action for <a> and <button> elements. Note the addition of the hover styles here not present in the previous example. Also supported is the .active state; apply it to indicate an active selection on a contextual list group item.
   *
   * @default false
   */
  action: boolean;

  /**
   * Add `.disabled` to a `.list-group-item` to make it appear disabled.
   *
   * @default false
   */
  disabled: boolean;

  /**
   * Want equal-width list group items when horizontal? Add .flex-fill to each list group item.
   *
   * @default false
   */
  flexFill: boolean;

  /**
   * When rendering list items a links, you can give href attribute the value.
   * @default undefined
   */
  href: string;
}>;
